### PR TITLE
Raspberry Pi Build

### PR DESCRIPTION
**Pull request by rukkus**
I managed to get docker cloud agent to build and run on a Raspberry Pi, I'm not sure what the plan is around different architecture support but maybe this pull request might help.

There is a prebuilt arm deb that works on raspbian jessie available in the releases section. I had to modify the Dockerfile and some of the bash scripts so merging into master as is would be a bad idea but hopefully it might be of some use.

Its very cool to be able to add such a small cheap system as a docker cloud node :)

### CODE REVIEW

**Comment by tifayuki** [comment]
@rukkus 

It is interesting run Docker Cloud on Raspberry Pi. However, to make it work, I think we have to make other changes so that the agent downloads the ARM version of docker instead of the x64 one.

Also, we are going to change the node provisioning to use docker native tools, and this repo will be deprecated soon.

I guess the support of Raspberry Pi will not be supported in the agent.

Thank you

**Comment by mrmachine** [comment]
Does this mean Docker Cloud Agent (and BYON) will never officially work on _any_ ARM 64-bit architecture, or just RPI? If so, that sucks. I was really looking forward to using my odroid-c2 as BYON as a test sandbox and for light workloads at home.

**Comment by tifayuki** [comment]
@mrmachine 

To support ARMs, the agent has to download a a ARM version of docker, and currently we only support downloading the x64 version of docker. 

There could be a lot of code changes to support ARMs. As the agent is going to be deprecated soon, we are not going to support ARM nodes here. Instead, when we migrate to use docker native tools to provision the node, we will think about the ARM support.

**Comment by mrmachine** [comment]
@tifayuki When is docker cloud agent going away, and what is it's replacement? If it's going to be a long time (I haven't seen it announced that Docker Cloud Agent is deprecated?), and then more time again until ARM is supported, it might be worth taking a closer look at this PR which claims to have Docker Cloud Agent built and running on ARM?

**Comment by tifayuki** [comment]
@mrmachine 
There is no ETA yet, it is on our roadmap. 
Even though I merge this PR, the agent will not work unless we changed the server end logic, which is not going to happen, AFAIK.

Moreover, this PR simply changes amd64 to arm, which will break the build of the agent for x86-64 architecture.

**Comment by fermayo** [comment]
This will be supported when we support 1.12+ swarm clusters without the use of this agent

**Pull request closed without merging**
